version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    restart: always
    container_name: iot_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iot_data
      MYSQL_USER: iot_user
      MYSQL_PASSWORD: iot_password
    volumes:
      - db-data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - iot-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # IoT Data Collector App
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: iot_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: iot_user
      DB_PASSWORD: iot_password
      DB_NAME: iot_data
      PORT: 3000
      HOST: 0.0.0.0
      # Add other environment variables as needed
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 1000
      DATA_RETENTION_ENABLED: true
      DATA_RETENTION_DAYS: 180
    volumes:
      # Optional: Mount logs directory if you want persistent logs
      - ./logs:/app/logs
    networks:
      - iot-network
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  iot-network:
    driver: bridge

volumes:
  db-data:
    driver: local